pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8
    environment:
      - NODE_ENV=development
    commands:
      - yarn install --no-progress
      - yarn build --release

  publish-vip:
    image: plugins/docker
    repo: tobiasmayr/gold
    tags: [ vip ]
    secrets: [ docker_username, docker_password ]
    build_args:
      - DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - DRONE_BRANCH=${DRONE_BRANCH}
    when:
      event: push
      branch: [ vip ]

  publish-vip-live:
    image: plugins/docker
    repo: tobiasmayr/gold
    auto_tag: true
    auto_tag_suffix: vip
    secrets: [ docker_username, docker_password ]
    build_args:
      - DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - DRONE_BRANCH=${DRONE_TAG}
    when:
      event: tag

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
