pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8
    environment:
      - NODE_ENV=development
    commands:
      - yarn install --no-progress
      - yarn build --release

  publish-dev:
    image: plugins/docker
    repo: tobiasmayr/gold
    tags: [ dev ]
    secrets: [ docker_username, docker_password ]
    build_args:
      - DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - DRONE_COMMIT=${DRONE_COMMIT}
    when:
      event: push
      branch: dev

  publish-live:
    image: plugins/docker
    repo: tobiasmayr/gold
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

branches: [ dev ]
