version: '3'
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test

  web:
    image: index.docker.io/tobiasmayr/gold:dev
    restart: always
    #volumes:
    #  - ${BANNER}:/app/public/banner01.jpg
    ports:
      - 3005:3005
    environment:
      - PORT=3005
      - NODE_ENV=production
      - HOST=test.g-old.org
      - DATABASE_URL=postgresql://user:password@db:5432/test
      - RECAPTCHA_SECRET=secret
      - RECAPTCHA_KEY=key

volumes: pgdata:
