/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const LOAD_PROPOSAL_START = 'LOAD_PROPOSAL_START';
export const LOAD_PROPOSAL_SUCCESS = 'LOAD_PROPOSAL_SUCCESS';
export const LOAD_PROPOSAL_ERROR = 'LOAD_PROPOSAL_ERROR';
export const ADD_PROPOSAL = 'ADD_PROPOSAL';
export const CREATE_LIKE_START = 'CREATE_LIKE_START';
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS';
export const CREATE_LIKE_ERROR = 'CREATE_LIKE_ERROR';
export const DELETE_LIKE_START = 'DELETE_LIKE_START';
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS';
export const DELETE_LIKE_ERROR = 'DELETE_LIKE_ERROR';
